language: cpp

matrix:
  include:
    - os: linux
      compiler:
        - clang
      before_install:
        - git submodule update --init --recursive
      install:
        - sudo apt-get install libboost-all-dev
      script:
        - ./build-linux.sh
      before_deploy:
        - git config --local user.name "zone117x"
        - git config --local user.email "zone117x@gmail.com"
        - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      deploy:
        provider: releases
        api_key:
          secure: 1HK5Frxf2g4d3rP2lTVcZPNI5NRpcUsj5PFQfLQMU/O/q7eFPnLoVkbRzLejSNDyi9VPBMAhi/jlHDMGmLrEz8E8vlMU5ghzctoY+QeiS/ZhLVyk+P96pV8f48G9u3VEg7b1bq72RbVod84SOsNnZjuqHMBGXAlPkO38hhAmML1e/tkWgblECoz7COc64gqaJdqoozXrk9XWVO53zo6Tzkp8lYh5oc18JoSmuQ8YirPPKZ3taRhsg9YGBANJzoTiKQoT+nX7nBztoKmZ0gUC5SYtQ+SsDAiOfx2DUUQINgd6rznxvaTxWeUVMSxpzLq68sqMSigmo2xY9gxgKuoILZW4AvVI+PllB6qWQ5xZfqfoDrv34mrMjpreULRLiVqLuzg/Cp/WFTpw6veM7ut4A4wLntqaOPqFIs9qo+OcSioTaVGsFLO19TwQIeqCkNsZZlL5xEmuFKfJgdIQBW1EXZXRLIQOpAT/8Z344J/kujn+gpKvR5Mps8284vo57IzvEFjJyB9zPKvJHE+vyd+mdfV/y/w8M/1KEaJy+mYYS7BllVolvSFdRQN4CgaD0BMvNVgg85RLov2jpiNccPTQQjgXe3nDkYWJUUXIBw37mmBtlYlkFp1jihVoPkGdkUT/eCkcJHPbLyF5a8tiBQxTtVLOoXzrKtqrIAzk0AqvwqI=
        file: solidity/build/libsolc/libsolc.so
        on:
          repo: hosho/solc-build
        skip_cleanup: true

    - os: osx
      osx_image: xcode9.3
      before_install:
        - git submodule update --init --recursive
      install:
        # - brew install boost
      script:
        - ./build-macos.sh
      before_deploy:
        - git config --local user.name "zone117x"
        - git config --local user.email "zone117x@gmail.com"
        - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      deploy:
        provider: releases
        api_key:
          secure: 1HK5Frxf2g4d3rP2lTVcZPNI5NRpcUsj5PFQfLQMU/O/q7eFPnLoVkbRzLejSNDyi9VPBMAhi/jlHDMGmLrEz8E8vlMU5ghzctoY+QeiS/ZhLVyk+P96pV8f48G9u3VEg7b1bq72RbVod84SOsNnZjuqHMBGXAlPkO38hhAmML1e/tkWgblECoz7COc64gqaJdqoozXrk9XWVO53zo6Tzkp8lYh5oc18JoSmuQ8YirPPKZ3taRhsg9YGBANJzoTiKQoT+nX7nBztoKmZ0gUC5SYtQ+SsDAiOfx2DUUQINgd6rznxvaTxWeUVMSxpzLq68sqMSigmo2xY9gxgKuoILZW4AvVI+PllB6qWQ5xZfqfoDrv34mrMjpreULRLiVqLuzg/Cp/WFTpw6veM7ut4A4wLntqaOPqFIs9qo+OcSioTaVGsFLO19TwQIeqCkNsZZlL5xEmuFKfJgdIQBW1EXZXRLIQOpAT/8Z344J/kujn+gpKvR5Mps8284vo57IzvEFjJyB9zPKvJHE+vyd+mdfV/y/w8M/1KEaJy+mYYS7BllVolvSFdRQN4CgaD0BMvNVgg85RLov2jpiNccPTQQjgXe3nDkYWJUUXIBw37mmBtlYlkFp1jihVoPkGdkUT/eCkcJHPbLyF5a8tiBQxTtVLOoXzrKtqrIAzk0AqvwqI=
        file: solidity/build/libsolc/libsolc.dylib
        on:
          repo: hosho/solc-build
        skip_cleanup: true