version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - arch: x86
  - arch: x64
clone_folder: c:\solc-build
cache:
- C:\solc-build\boost_1_67_0-msvc-14.1-32.exe
- C:\solc-build\boost_1_67_0-msvc-14.1-64.exe
branches:
  only:
    - master
skip_tags: true
before_build:
  - set RELEASE_TITLE=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%
  - echo %RELEASE_TITLE%
  - git submodule update --init --recursive || exit

build_script:
  - build-win.bat %arch% || exit
  - 7z a win-%arch%.zip %APPVEYOR_BUILD_FOLDER%/solidity/build-Release-x%arch%/libsolc/Release/solc.dll || exit
  - appveyor PushArtifact win-%arch%.zip
deploy:
  tag: $(RELEASE_TITLE)
  release: $(RELEASE_TITLE)
  description: Solc lib
  provider: GitHub
  auth_token:
    secure: 28Oe+p1iAuhqRSPD1+oChgzTr52yyjmA+0c64Ca8dCrlI2VHJ4dy+B40dZjF93on
  artifact: win-%arch%.zip
  force_update: true
  draft: false
  prerelease: false
  on:
    branch: master