version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\solc-build
cache:
- C:\solc-build\boost_1_67_0-msvc-14.1-32.exe
- C:\solc-build\boost_1_67_0-msvc-14.1-64.exe
- C:\local\boost_1_67_0
build_script:
- cmd: >-
    git submodule update --init --recursive || exit /b

    build-win.bat x64 || exit /b

    build-win.bat x86 || exit /b

    7z a win-libs.zip %APPVEYOR_BUILD_FOLDER%/build/* || exit /b

    appveyor PushArtifact win-libs.zip || exit /b
