version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\solc-build
cache:
- C:\solc-build\boost_1_67_0-msvc-14.1-32.exe
- C:\solc-build\boost_1_67_0-msvc-14.1-64.exe
- C:\local\boost_1_67_0
build_script:
- cmd: >-
    git submodule update --init --recursive || exit /b

    build-win.bat x64 || exit /b

    build-win.bat x86 || exit /b

    7z a win-libs.zip %APPVEYOR_BUILD_FOLDER%/build/* || exit /b

    appveyor PushArtifact win-libs.zip || exit /b
- cmd: set DATE=%DATE:~10,4%-%DATE:~7,2%-%DATE:~4,2%
deploy:
  tag: $(DATE)
  release: $(DATE)
  description: Solc lib
  provider: GitHub
  auth_token:
    secure: 4LMTwnlMHXDHt0CoHUU0nuCVy3y3VC+uiMgzR9GrLdZKQAEwZ51MPUxsnbQRYmJK
  artifact: win-libs.zip
  force_update: true
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true