version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\solc-build
cache:
- C:\solc-build\boost_1_67_0-msvc-14.1-32.exe
- C:\solc-build\boost_1_67_0-msvc-14.1-64.exe
branches:
  only:
    - master
skip_tags: true

build_script:
- cmd: >-
    set RELEASE_TITLE=%DATE:~10,4%-%DATE:~7,2%-%DATE:~4,2%
    echo %RELEASE_TITLE%
    git submodule update --init --recursive || exit
    build-win.bat x64 || exit
    build-win.bat x86 || exit
    7z a win-libs.zip %APPVEYOR_BUILD_FOLDER%/build/* || exit
    appveyor PushArtifact win-libs.zip
deploy:
  tag: $(RELEASE_TITLE)
  release: $(RELEASE_TITLE)
  description: Solc lib
  provider: GitHub
  auth_token:
    secure: 4LMTwnlMHXDHt0CoHUU0nuCVy3y3VC+uiMgzR9GrLdZKQAEwZ51MPUxsnbQRYmJK
  artifact: win-libs.zip
  force_update: true
  draft: false
  prerelease: false
  on:
    branch: master